name: Validate

on:
  push:
  pull_request:

jobs:
  spellcheck_lint:
    name: ShellCheck
    runs-on: ubuntu-latest
    steps:
      - name: ðŸ“¦ Checkout the repository
        uses: actions/checkout@v2

      - name: âœ… Run PySpelling as a GitHub action
        continue-on-error: true
        uses: rojopolis/spellcheck-github-actions@0.14.0
        with:
          config_path: spellcheck.yml

  python_linting:
    name: Python linting
    runs-on: ubuntu-latest
    steps:
      - name: ðŸ“¦ Check out source repository
        uses: actions/checkout@v2
      - name: ðŸ“¦ Set up Python environment
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"
      - name: âœ… flake8 Lint
        continue-on-error: true
        uses: py-actions/flake8@v1
        with:
          ignore: "F401"
          max-line-length: "120"

  validate:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - name: HACS validation
        continue-on-error: true
        uses: "hacs/action@main"
        with:
          category: "integration"